services:
  postgres:
    image: postgres:15
    container_name: notes-postgres
    restart: always
    environment:
      POSTGRES_USER: notes_user
      POSTGRES_PASSWORD: notes_pass
      POSTGRES_DB: notes_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: notes-adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  pgdata:
